# Generated by Django 2.2.1 on 2022-07-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaltech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='generaltech.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='generaltech.Tag'),
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
