# Generated by Django 2.2.1 on 2022-07-15 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generaltech', '0002_auto_20220715_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='uri',
            field=models.CharField(default='article-one', max_length=256),
            preserve_default=False,
        ),
    ]
