# Generated by Django 2.2.1 on 2022-07-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaltech', '0003_auto_20220715_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
