# Generated by Django 2.2.1 on 2022-07-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaltech', '0004_auto_20220715_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='sluf',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
