# Generated by Django 2.2.1 on 2022-07-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generaltech', '0005_tag_sluf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='sluf',
            new_name='slug',
        ),
    ]
