# Generated by Django 2.2.1 on 2022-07-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaltech', '0007_article_titleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='titleImage',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
