# Generated by Django 3.2 on 2022-07-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generaltech', '0009_auto_20220720_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='_generaltech_article_related_articles_+', to='generaltech.Article'),
        ),
    ]
